TOKEN = ''
API_WHEATHER_TOKEN = ''

#словарь для перевода погоды
weather_descriptions = {
    "thunderstorm with light rain": "гроза с небольшим дождем",
    "thunderstorm with rain": "гроза с дождем",
    "thunderstorm with heavy rain": "гроза с сильным дождем",
    "light thunderstorm": "слабая гроза",
    "thunderstorm": "гроза",
    "heavy thunderstorm": "сильная гроза",
    "ragged thunderstorm": "неравномерная гроза",
    "thunderstorm with light drizzle": "гроза с небольшой моросью",
    "thunderstorm with drizzle": "гроза с моросью",
    "thunderstorm with heavy drizzle": "гроза с сильной моросью",
    "light intensity drizzle": "небольшая морось",
    "drizzle": "морось",
    "heavy intensity drizzle": "сильная морось",
    "light intensity drizzle rain": "небольшой моросящий дождь",
    "drizzle rain": "моросящий дождь",
    "heavy intensity drizzle rain": "сильный моросящий дождь",
    "shower rain and drizzle": "ливень с моросью",
    "heavy shower rain and drizzle": "сильный ливень с моросью",
    "shower drizzle": "ливень с моросью",
    "light rain": "небольшой дождь",
    "moderate rain": "умеренный дождь",
    "heavy intensity rain": "сильный дождь",
    "very heavy rain": "очень сильный дождь",
    "extreme rain": "экстремальный дождь",
    "freezing rain": "ледяной дождь",
    "light intensity shower rain": "небольшой ливневый дождь",
    "shower rain": "ливневый дождь",
    "heavy intensity shower rain": "сильный ливневый дождь",
    "ragged shower rain": "неравномерный ливневый дождь",
    "light snow": "небольшой снег",
    "snow": "снег",
    "heavy snow": "сильный снег",
    "sleet": "дождь со снегом",
    "light shower sleet": "небольшой дождь со снегом",
    "shower sleet": "дождь со снегом",
    "light rain and snow": "небольшой дождь и снег",
    "rain and snow": "дождь и снег",
    "light shower snow": "небольшой ливневый снег",
    "shower snow": "ливневый снег",
    "heavy shower snow": "сильный ливневый снег",
    "mist": "туман",
    "smoke": "дым",
    "haze": "дымка",
    "sand": "песок",
    "dust": "пыль",
    "volcanic ash": "вулканический пепел",
    "squalls": "шквалы",
    "tornado": "торнадо",
    "clear sky": "ясное небо",
    "few clouds": "малооблачно",
    "scattered clouds": "рассеянные облака",
    "broken clouds": "разорванные облака",
    "overcast clouds": "пасмурно"
}

